_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 128
beta_1:
    value: 0.0001
beta_2:
    value: 0.02
epochs:
    value: 1
learning_rate:
    value: 1e-05
num_timesteps:
    value: 1000
unet_hidden_size:
    value: 128
